# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 090c77e359a3d2efb2e2a7b033a33444ad9ef4c7356c9e2a4fd69fb1c1041e157e16085c9af11f4cf223561fadb97e96e5a51da1e181f740ae3ff3b8129e92eb
  test_twilio_sid: AC3a059f4f5685df84c793e32ed7cb2357
  test_twilio_token: a5cfac02e903558d15b5c1c8bd3388a7
  twilio_sid: AC423dc892eded187de44e58e39d6bbc3d
  twilio_token: 13a9adc57d31d0aa2b8aaaf8fb84a3d7
  twilio_number: '18472326161'

test:
  secret_key_base: ddeb2e26a01ae0a69dc7cfb824f4822470d44e73a0251d79c945841072f4dad9d18b2dd3bd5766de4dd80bc2ab95305f345dae63f9896a1a9c76e50aae0e4121

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
